AWSTemplateFormatVersion: 2010-09-09
Description: create ec2 instance

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:!Sub "my-unique-bucket-${AWS::AccountId}-${AWS::Region}"
  
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: "MyEMRCluster"
      LogUri:!Sub "s3://${S3Bucket}/logs/"
      ReleaseLabel: "emr-6.4.0"
      Applications:
        - Name: "Hadoop"
        - Name: "Spark"
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m5.xlarge
      JobFlowRole: "EMR_EC2_DefaultRole" # Ensure this role exists or create it
      ServiceRole: "EMR_DefaultRole" # Ensure this role exists or create it
      VisibleToAllUsers: true
      EbsRootVolumeSize: 32
      Tags:
        - Key: "Name"
          Value: "MyEMRCluster"
