---
AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance, an S3 bucket, and an EMR Cluster

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9  # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Vita
  
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sahil123 # Ensure this bucket name is globally unique

  # Example of adding an EMR Cluster
  MyEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: MyCluster1
      ReleaseLabel: emr-6.4.0
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m5.xlarge
        TerminationProtected: false
      Applications:
        - Name: Hadoop
        - Name: Spark
      VisibleToAllUsers: true
      LogUri: !Sub 's3://${WebAppBucket}/logs/'
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole



AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a Glue database, crawler, and ETL job using an existing IAM role.

Resources:
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties: 
      CatalogId: 966884175598
      DatabaseInput: 
        Name: my_database123

  GlueCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: arn:aws:iam::966884175598:role/LabRole
      DatabaseName: !Ref GlueDatabase
      Name: my_crawler123
      Targets:
        S3Targets:
          - Path: 's3://sahil123/input/data.csv'
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)' # Run daily at 12:00 UTC

  GlueETLJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: csv_to_parquet_job
      Role: arn:aws:iam::966884175598:role/LabRole
      Command:
        Name: glueetl23
        ScriptLocation: 's3://sahil123/script/transform_script.py'
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': 's3://sahil123/temp/'
        '--job-bookmark-option': 'job-bookmark-enable'
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: '4.0'
      NumberOfWorkers: 10
      WorkerType: G.1X

Outputs:
  GlueDatabaseName:
    Description: Name of the Glue Database
    Value: !Ref GlueDatabase

  GlueCrawlerName:
    Description: Name of the Glue Crawler
    Value: !Ref GlueCrawler

  GlueETLJobName:
    Description: Name of the Glue ETL Job
    Value: !Ref GlueETLJob

